### ISSUE TITLE
Harmony Fails to Generate Code

### ISSUE THREAD

**Issue by UmsignedInteger** [Microchip-MPLAB-Harmony/bootloader#16]
ATSAMD21G17D on custom board
mhc 3.8.2
csp 3.10.0
core 3.10.0
bootloader 3.5.0

I have a working app using FreeRTOS with 5 tasks.
I want to add bootloader.
However, I get this error when adding the serial memory bootloader components:
(Sorry for formatting - it is doing its own thing...)

*An exception was thrown while attempting to markup a template file: C:\Microchip\harmony\v3\bootloader\templates\system\tasks.c.ftl
<FreeMarker>[Error]: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> BTL_RTOS_STACK_SIZE  [in template "tasks.c.ftl" at line 4, column 32]
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
FTL stack trace ("~" means nesting-related):
	- Failed at: #assign BTL_STACK_SIZE = (BTL_RTOS_ST...  [in template "tasks.c.ftl" at line 4, column 5]*

I don't have the luxury of removing FreeRTOS as was advised on a previous post with similar issue back in July.

What is current status of this issue?
What is a workaround to get functioning RTOS + Bootloader?

Thanks in advance
UI

**Comment by amitraddi** [comment]
Hi @UmsignedInteger,
Thanks for reporting the issue. Currently only UDP and USB Device HID bootloader in live-update mode support RTOS.
There is no support for RTOS for all other bootloaders.

**Comment by UmsignedInteger** [comment]
Hi amitraddi,

Thank you for update.
My use case is for background loading of SPI Flash chip with a new application (bootloader input).
Then on reboot, run serial memory bootloader to flash this new app into SAMD21, jump to new App and run.
Pretty straight forward.

My experience with PIC32s suggested that multiple custom linker files and careful planning was essential for bootloader success.
My early exposure to SAM chips and some Harmony sample bootloader apps suggests that things may not be so difficult.

Without thinking it through, I was concerned that the lack of example Harmony bootloader input apps with the FreeRTOS switched on was suggesting some intrinsic problem. Having seen a previous post solution was to just turn FreeRTOS off! However, being just another task, I assume that this should not be a problem.

The example app for serial memory bootloader following reset, should be able to be used almost "out of the box"

Please correct me if this is not correct.

UI

**Comment by amitraddi** [comment]
Hi @UmsignedInteger 
As per your use case, the existing serial memory bootloader should work almost out of box. 

1. Harmony 3 Serial memory bootloader reads the raw binary from external flash and programs into the internal. this is configurable through MHC as part of bootloader repo. As this is meant to be a standalone bootloader project we run it in Bare-Metal environment.
2. For getting the application binary in external flash we do not provide any MHC component like bootloader. but we do have a demo programmer project which receives application over UART from Host PC and loads the application in external flash and triggers reset so that bootloader can now read it and program in internal flash

Here is the link for the demonstration and more information on how it works
https://microchip-mplab-harmony.github.io/bootloader_apps_serial_memory/apps/spi_flash_bootloader/readme.html

https://microchip-mplab-harmony.github.io/bootloader_apps_serial_memory/apps/fs/spi/readme.html

Hope this helps

**Comment by UmsignedInteger** [comment]
Thank you.
That is helpful.
